### PR TITLE
add translations to registration page

### PR DESCRIPTION
**Pull request by nivemaham**
Add translations for keycloak

### CODE REVIEW

**Review by peyman-mohtashami — APPROVED** [review]
It's good. 
I found out if ```# encoding: utf-8``` added to the top of the message file, we can use special chars.
This is the keycloak pattern for some languages for example Russian.

**Comment by nivemaham** [comment]
> # encoding: utf-8

Yes. I read about it. Although, it mentioned the encoding should be mentioned as header and I wasn't sure where would that go.
plus, I though the value in the message file should be uft-8 encoded, if we are using that. 
i can try that out.

**Comment by peyman-mohtashami** [comment]
Yes, header means the first line of the file. I checked it and works. But for now I think your implementation is fine.

**Comment by nivemaham** [comment]
yes, I have tried that too. It works.

**Comment by nivemaham** [comment]
I have changed the translation properties with special char with encoding. Thanks for the suggestion @peyman-mohtashami

**Pull request merged**
